# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09e24ea79fed954151bf47a33e2299dbcd7cb89c5c3b2f016f9c3fe12c5b0d8faf4df20027565c4587d57c34b322a5831792ade51ad8e7df8e4e548ef1611847

test:
  secret_key_base: 4081413bfec7fe1757620053e5d90ddfe0525f8af7d2e44d6285ab137eb78a111d1da355ace7538041772e6caa96f6fba1091f4c110998c0dbbbffa92a71a704

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
